yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
# yatabe URL Configuration
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls'))
]

handler404 = 'core.views.page_not_found'

handler403 = 'core.views.permission_denied'

handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.db.models import UniqueConstraint
from django.contrib.auth import get_user_model
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=20, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        related_name='group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date'),
        verbose_name = 'Пост',
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    author = models.ForeignKey(
        User,
        verbose_name="comments",
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name='following'
    )
    UniqueConstraint(
        fields=['user', 'author'],
        name='unique_follow'
    )

yatube/posts/forms.py
from xml.etree.ElementTree import Comment
from django.utils.translation import gettext_lazy as _
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': _('Текст'),
        }
        labels = {
            'group': _('Группа'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from tkinter import PAGES
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm


PAGES = 10


# Главная страница
def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


# Список групп
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).all()
    paginator = Paginator(posts, PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


# Профайл пользователя
def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_count = posts.count()
    if request.user.is_authenticated:
        if Follow.objects.filter(user=request.user, author=user).exists():
            following = True
        else:
            following = False
    else:
        following = False
    context = {
        'author': user,
        'user': user,
        'posts': posts,
        'page_obj': page_obj,
        'count_posts': post_count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


# Запись пользователя
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_count = Post.objects.filter(author=post.author).count()
    comments = Comment.objects.filter(post_id=post_id)
    form_comments = CommentForm(request.POST or None)
    context = {
        'post': post,
        'post_count': post_count,
        'comments': comments,
        'form_comments': form_comments
    }
    return render(request, 'posts/post_detail.html', context)


# Создание записи
@login_required
def post_create(request):
    request.method == 'POST'
    form = PostForm(
        request.POST,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    return render(request, 'posts/create_post.html', {'form': form})


# Изменение записи
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:profile', post.author)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)

# Добавление комментария


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

# Лента подписок


@login_required
def follow_index(request):
    user = request.user
    posts = Post.objects.filter(author__following__user=user)
    paginator = Paginator(posts, PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Мои подписки',
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)

# Подписка на автора


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect(
            'posts:profile',
            username=username
        )
    follower = Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    if follower is True:
        return redirect(
            'posts:profile',
            username=username
        )
    Follow.objects.create(user=request.user, author=author)
    return redirect(
        'posts:profile',
        username=username
    )
# Отписка от автора


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}           
  <div class="card-header">
   {% if is_edit %}
    Редактировать пост
   {% else %}
    Новый пост
   {% endif %}
   </div>
     <div class="card-body">        
      {% if is_edit %}
      <form method="post" enctype="multipart/form-data" action= "{% url 'posts:post_edit' post.id %}">
      {% else %}
      <form method="post" enctype="multipart/form-data" action= "{% url 'posts:post_create' %}">
      {% endif %}
         <input type="hidden" name="csrfmiddlewaretoken" value="">
          {% csrf_token %}
          <label for="id_image">
            Картинка                      
          </label>
          <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                            
           <div class="form-group row my-3 p-3">
            <label for="id_text">
             Текст поста                  
            <span class="required text-danger" >*</span>                  
            </label>
            
            {{form.text}}
            {% if is_edit %}              
              <small id="id_text-help" class="form-text text-muted">
                 Текст нового поста
               </small>
            {% else %}
              <small id="id_text-help" class="form-text text-muted">
              Текст ре поста
              </small>
              {% endif %}                    
            </div>            
            <div class="form-group row my-3 p-3">
            <label for="id_group">
               Group                  
            </label>
               {{ form.group }}
            <small id="id_group-help" class="form-text text-muted">
             Группа, к которой будет относиться пост
            </small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
              </button>
            </div>
          </form>
          </div>
 {% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load cache %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  {% if post.group %}
  <li>    
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  </li>
  </li>
   <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
  </ul>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
{{group.title}}
{% endblock %}}
{% block content %}
<h1>{{ group.title }}</h1>
<p> {{ group.description }}</p>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:profile' post.author %}">
    все посты пользователя
    </a>
    <li>
    <a href="{% url 'posts:post_detail' post.id %}">
      подробная информация 
    </a>
  </li>
{% if not forloop.last %} <hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}  
    

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% cache 20 index_page %}
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  {% if post.group %}
  <li>    
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  </li>
  </li>
   <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
  </ul>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  {% endcache %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load user_filters %}
{%block title%}
Пост 
{{post.text|truncatechars:30}}
{% endblock %} 

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li> 
              <li class="list-group-item">
                Группа: {{group.title}}
                {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
                {% endif %}
                
              </li>
              <li class="list-group-item">
                Автор: {{post.author.get_full_name}}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">

              Всего постов автора:  <span >{{posts.count}}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{post.text}} 
          </p>
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
           {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form_comments.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
<p> Комментарии </p>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}                
        </article>
      </div> 
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
Профайл пользователя {{author.get_full_name}}
{% endblock %} 

{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{author.get_full_name}} </h1>
        <h3>Всего постов: {{posts.count}} </h3>
        {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    {% if user.username != post.author %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
      {% endif %}
   {% endif %}
        {% for post in page_obj %}   
        <article>
          <ul>
            <li>
              Автор: {{post.author.get_full_name}}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{post.text}} 
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>        
        {% if not forloop.last %} <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      
{% endblock %} 